//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook_Project.Models
{
    using System;
    using System.Collections.Generic;

    public partial class friendRequstes
    {
        public int Id { set; get; }

        public int id_UserSender { get; set; }
        public virtual userinfo UserSender { get; set; }

        public int id_userFriend { get; set; }
        public virtual userinfo userFriend { get; set; }
    }
}
