//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook_Project.Models
{
    using System;
    using System.Collections.Generic;

    public partial class post
    {
        public int Id { get; set; }
        public string postone { get; set; }
        public int iduserinfo { get; set; }
        public int role { get; set; }
        public virtual userinfo userinfo { get; set; }
        public virtual List<comments> comments { get; set; }
        public virtual List<reacts> reacts { get; set; }
    }
}
