//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook_Project.Models
{
    using System;
    using System.Collections.Generic;

    public partial class reacts
    {
        public int Id { get; set; }
        public int Like { get; set; }
        public int idpost { get; set; }

        public int iduserinfo { get; set; }
        public virtual post post { get; set; }
        public virtual userinfo userinfo { get; set; }
    }
}
