//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook_Project.Models
{
    using System;
    using System.Collections.Generic;

    public partial class userinfo
    {
        public int Id { get; set; }
        public string Fname { get; set; }
        public string lname { get; set; }
        public string photo { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string password { get; set; }

        public virtual List<reacts> Reacts { get; set; }
        public virtual List<comments> Comments { get; set; }
        public virtual List<post> posts { get; set; }
        public virtual List<friends> friends { get; set; }
        public virtual List<friendRequstes> friendRequstes { get; set; }
    }
}
